#### Jekyll Global Configuration ####
title: "Arknights Library" # the name of your site, e.g. ACME Corp.
authors: "Doctors"
project_url: "https://github.com/kiraio-moe/Arknights-Library"
domain: kiraio-moe.github.io # if you want to force HTTPS, specify the domain without the http at the start, e.g. example.com
url: "https://kiraio-moe.github.io" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "/Arknights-Library" # the subpath of your site, e.g. /blog. Default: ./
description: >- # this means to ignore newlines until "baseurl:"
    A collections of Assets, Resources and Tools to boost up your experiences with Arknights. Developed by Doctors for Doctors.
logo:
destination: ./_site # Where built site should stored.

# Date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
date_format: "%d %b, %Y"

lang: "en" # language
dir: "ltr" # page direction
# generate social links in footer
# social:
#   name: 
#   links:
#     - telegram: https://t.me/
#     - github: https://github.com/
#     - discord: https://discord.gg/

# google_site_verification:
# google_analytics:
# webmaster_verifications:
#   google: 1234
#   bing: 1234
#   alexa: 1234
#   yandex: 1234
#   baidu: 1234

exclude:
    - "*.gem"
    - "*.gemspec"
    - scripts
    - "LICENSE"
    - "README.md"
    - "frontmatter.json"
    - "Gemfile"
    - "*.lock"
